FROM node:20 AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM base
COPY --from=build /app /app

CMD "pnpm install --frozen-lockfile -f"

EXPOSE 8080

CMD sh -c "pnpm migrate:up && pnpm dev"
